FROM nginx:alpine

RUN adduser -D -g mahesh mahesh

COPY --chown=mahesh:mahesh nginx.conf /etc/nginx/nginx.conf

COPY --chown=mahesh:mahesh index.html /usr/share/nginx/html/index.html

RUN chown -R mahesh:mahesh /var/cache/nginx && chmod 775 /var/cache/nginx

RUN touch /var/run/nginx.pid && \
  chown -R mahesh:mahesh /var/run/nginx.pid && \
  chown -R mahesh:mahesh /var/cache/nginx

USER mahesh
# To set the port as a class path
ENV port 8080
EXPOSE ${port}

CMD ["nginx", "-g", "daemon off;"]
