# Docker Image Name
FROM httpd:2.4.63-alpine3.21

# Switch to the non-root user
RUN groupadd -g 1001 mahesh && useradd -u 1001 -g 1001 mahesh

# Install depency packages for ps command
# RUN apt update && apt install -y procps curl && rm -rf /var/lib/apt/lists/*

RUN chown -R mahesh:mahesh /usr/local/apache2/

EXPOSE 8080
# EXPOSE 80/TCP # This will not epose to host machine

# Start the Apache httpd service as non-root user
# Since the CMD/ENTRYPOINT already defined at the image level we don't need to define manually
# CMD/ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
# CMD '/usr/sbin/httpd -DFOREGROUND &'
# CMD ["httpd-foreground"]

USER mahesh
CMD ["httpd-foreground"]
